name: message
options:
  bundleIdPrefix: com.synrc
targets:
  Message:
    type: application
    platform: [iOS, macOS]
    deploymentTarget:
      iOS: "17.0"
      macOS: "14.4"
    sources:
      - path: message
    settings:
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 6.2
    dependencies:
      - sdk: CoreData.framework
