name: message-ci
options:
  bundleIdPrefix: com.synrc
targets:
  Message:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - project.yml
          - README.md
          - .gitignore
    settings:
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: "1.0"
      CURRENT_PROJECT_VERSION: "1"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
      SWIFT_VERSION: 5.9
    dependencies:
      - sdk: CoreData.framework
